version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "major"
  - package-ecosystem: "terraform"
    directory: "minor"
    ignore:
      dependency-name: '*'
      update-types: ["version-update:semver-major"]
  - package-ecosystem: "terraform"
    directory: "patch"
    ignore:
      dependency-name: '*'
      update-types: ["version-update:semver-major", "version-update:semver-minor"]