version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "major"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "no-patch"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "minor"
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "al"
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "terraform"
    directory: "springx"
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "terraform"
    directory: "patch"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "terraform"
    directory: "kernel"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "json"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "hg"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "golang"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "godot"
    schedule:
      interval: daily
  - package-ecosystem: "terraform"
    directory: "maria"
    schedule:
      interval: daily